In [4]:
import ollama
ollama.pull('llama3')


{'status': 'success'}

In [34]:
import requests

OLLAMA_API_URL = "https://6817-34-125-222-127.ngrok-free.app/api/chat"

# JSON data
payload = {
    "model": "llama3",
    "messages": [
        { "role": "user", "content": "Hello!" }
    ]
}

response = requests.post(OLLAMA_API_URL, json=payload)

# Decode the response content
response_content_decoded = response.content.decode('utf-8')

# Parse JSON data
chunks = response_content_decoded.strip().split('\n')

# Initialize variables
full_text = ""
text_buffer = ""

# Loop through each chunk
for chunk in chunks:
    data = json.loads(chunk)
    content = data.get('message', {}).get('content', '')

    # Check for punctuation marks
    if content.endswith(('.', '!', '?', ',')):
        full_text += content + ""
    else:
        full_text += content

# Remove trailing whitespace
full_text = full_text.strip()

# Print the formatted text
print(full_text)


Hello! It's nice to meet you. Is there something I can help you with, or would you like to chat?


In [26]:
response.content.decode('utf-8')


'{"model":"llama3","created_at":"2024-06-09T10:41:04.300178735Z","message":{"role":"assistant","content":"Hello"},"done":false}\n{"model":"llama3","created_at":"2024-06-09T10:41:04.344391607Z","message":{"role":"assistant","content":"!"},"done":false}\n{"model":"llama3","created_at":"2024-06-09T10:41:04.38826088Z","message":{"role":"assistant","content":" It"},"done":false}\n{"model":"llama3","created_at":"2024-06-09T10:41:04.422576431Z","message":{"role":"assistant","content":"\'s"},"done":false}\n{"model":"llama3","created_at":"2024-06-09T10:41:04.455256206Z","message":{"role":"assistant","content":" nice"},"done":false}\n{"model":"llama3","created_at":"2024-06-09T10:41:04.487596026Z","message":{"role":"assistant","content":" to"},"done":false}\n{"model":"llama3","created_at":"2024-06-09T10:41:04.520001035Z","message":{"role":"assistant","content":" meet"},"done":false}\n{"model":"llama3","created_at":"2024-06-09T10:41:04.552608874Z","message":{"role":"assistant","content":" you"},"d

Hello! It's nice to meet you. Is there something I can help you with, or would you like to chat?


In [31]:
full_text = ""
text_buffer = ""
for chunk in messages:
    text_buffer += 
    if text_buffer.endswith("."):
        full_text += text_buffer
        text_buffer = ""

if text_buffer:
    full_text += text_buffer


TypeError: string indices must be integers

In [11]:
import json

data = response.content

messages = []

# Split data into lines and iterate over each line
for line in data.splitlines():
    # Parse JSON from each line
    message_data = json.loads(line)
    # Extract the content field from the message and append it to the messages list
    message_content = message_data.get('message', {}).get('content', '')
    messages.append(message_content)

# Filter out empty strings
messages = [message for message in messages if message]

# Print the extracted messages
for message in messages:
    print(message)


Hello
!
 It
's
 nice
 to
 meet
 you
.
 Is
 there
 something
 I
 can
 help
 you
 with
,
 or
 would
 you
 like
 to
 chat
?


In [14]:
# Split the data into individual messages
messages = data.decode('utf-8').split('\n')

# Remove empty strings and extract content from each message
messages = [json.loads(msg)['message']['content'] for msg in messages if msg.strip()]

# Concatenate the messages and format the sentence
formatted_sentence = ' '.join(messages).capitalize()

print(formatted_sentence)


Hello !  it 's  nice  to  meet  you .  is  there  something  i  can  help  you  with ,  or  would  you  like  to  chat ? 


In [1]:
import numpy as np
from transformers.pipelines.audio_utils import ffmpeg_microphone_live


/opt/anaconda3/envs/urdu/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# Use a pipeline as a high-level helper
from transformers import pipeline
pipe = pipeline("automatic-speech-recognition", model="openai/whisper-small")


Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [13]:
stream_chunk_s = 1.0
chunk_length_s = 0.5
SAMPLING_RATE = 16_000

mic = ffmpeg_microphone_live(
    sampling_rate=SAMPLING_RATE,
    chunk_length_s=chunk_length_s,
    stream_chunk_s=stream_chunk_s,
    stride_length_s=0.0,
)

audios = []
for i in range(2):
    audio = next(mic)['raw']
    audios.append(audio)


2024-06-10 13:58:01.426 ffmpeg[46206:5543023] WARNING: Add NSCameraUseContinuityCameraDeviceType to your Info.plist to use AVCaptureDeviceTypeContinuityCamera.


In [14]:
audios


[array([ 0.00012101,  0.0001231 ,  0.00012174, ..., -0.00137429,
         0.00074111,  0.00297782], dtype=float32),
 array([0.00480944, 0.00548853, 0.00524643, ..., 0.0052021 , 0.00428747,
        0.00293501], dtype=float32)]

In [15]:
audios_flattened = np.array(audios).flatten()
from IPython.display import Audio

Audio(audios_flattened, rate=SAMPLING_RATE, autoplay=True)


In [19]:
pipe(audios_flattened, generate_kwargs={'language': 'urdu'})


{'text': ' ام میرا نام شریعت ہے'}

In [1]:
import numpy as np
from transformers import pipeline
from IPython.display import Audio
from transformers.pipelines.audio_utils import ffmpeg_microphone_live

pipe = pipeline("automatic-speech-recognition", model="openai/whisper-small")

stream_chunk_s = 1.0
chunk_length_s = 0.5
SAMPLING_RATE = 16_000

mic = ffmpeg_microphone_live(
    sampling_rate=SAMPLING_RATE,
    chunk_length_s=chunk_length_s,
    stream_chunk_s=stream_chunk_s,
    stride_length_s=0.0,
)

audios = []
for i in range(2):
    audio = next(mic)['raw']
    audios.append(audio)

audios_flattened = np.array(audios).flatten()

Audio(audios_flattened, rate=SAMPLING_RATE, autoplay=True)

transcription = pipe("/Users/shehryarsohail-nu/Downloads/2024-06-12T19_18_14.111Z.wav", generate_kwargs={'language': 'urdu'})
print(transcription)


/opt/anaconda3/envs/urdu/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


KeyboardInterrupt: 

In [1]:
import numpy as np
from transformers import pipeline
from IPython.display import Audio
from transformers.pipelines.audio_utils import ffmpeg_microphone_live

pipe = pipeline("automatic-speech-recognition", model="openai/whisper-small")
transcription = pipe("/Users/shehryarsohail-nu/Downloads/2024-06-12T19_18_14.111Z.wav", generate_kwargs={'language': 'urdu'})


/opt/anaconda3/envs/urdu/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [2]:
print(transcription)


{'text': ' ہلو میرا نام شہری آر ہے'}


In [1]:
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
)
# from utils import (
#     remove_stopwords,
#     remove_english_alphabets,
#     replace_currency_symbols,
#     replace_numbers,
#     replace_phone_numbers,
#     replace_emails,
#     replace_urls,
#     remove_accents,
#     remove_punctuation,
#     normalize_whitespace
# )
from utils import preprocess


In [2]:
model_name = 'model/xlm-roberta-urdu'

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2,
    ignore_mismatched_sizes=True,
)


In [5]:
import torch.nn.functional as F


In [10]:
text = [
    "ام میرا نام شریعت ہے",
    "میں بہت پریشان ہوں۔",
    "اب میں بہتر محسوس کر رہا ہوں آپ کی مدد کے لیے شکریہ"
]

text = [preprocess(txt) for txt in text]
input_ids = tokenizer(text, max_length=512, padding=True, truncation=True, return_tensors="pt")
output = model(**input_ids)
output.logits


tensor([[ 1.8042, -2.4612],
        [-0.8137,  0.4345],
        [ 1.2709, -1.9849]], grad_fn=<AddmmBackward0>)

In [13]:
out = F.softmax(output.logits, dim=1)[:, 1]*100
out


tensor([ 1.3851, 77.6987,  3.7119], grad_fn=<MulBackward0>)

In [17]:
out.mean().item()


27.598588943481445

In [15]:
# Load model directly
from transformers import AutoProcessor, AutoModelForTextToSpectrogram

processor = AutoProcessor.from_pretrained("TheUpperCaseGuy/Guy-Urdu-TTS")
model = AutoModelForTextToSpectrogram.from_pretrained("TheUpperCaseGuy/Guy-Urdu-TTS")


In [6]:
text = "آپ ایک اے آئی انزائٹی تھراپسٹ ہیں جس کا نام اوللاما ہے۔ آپ کا کام ان لوگوں کو تسلی دینا ہے جو انزائٹی کا شکار ہیں۔ آپ کا مقصد انہیں پرسکون کرنا اور بات چیت کے ذریعے مدد فراہم کرنا ہے۔ اگر وہ مشورہ طلب کریں، تو انہیں بہترین مشورہ دیں۔ آپ صرف اردو میں بات کریں گے۔ ایک بھی لفظ یا حرف انگریزی میں نہ ہو۔ کسی بھی صورت میں انگریزی کا استعمال نہ کریں۔ انگریزی میں بات کرنے سے مریض کو شدید تکلیف ہوگی، اور آپ یہاں مدد کرنے کے لیے ہیں نہ کہ تکلیف دینے کے لیے۔ یہ انتہائی ضروری ہے کہ آپ ہر صورت میں صرف اردو میں جواب دیں۔ صارف اردو میں لکھے گا، اور آپ اردو میں ہی جواب دیں گے۔ یہ نہ بتائیں کہ آپ ایک اے آئی ماڈل ہیں۔ آپ کو ایک انسان کی طرح بات کرنی ہے۔"


In [31]:
from transformers import pipeline, set_seed

pipe = pipeline(model="facebook/mms-tts-urd-script_arabic")
output = pipe(text)

set_seed(42)

audio = output["audio"]
sampling_rate = output["sampling_rate"]

print(sampling_rate)


Some weights of the model checkpoint at facebook/mms-tts-urd-script_arabic were not used when initializing VitsModel: ['flow.flows.0.wavenet.in_layers.0.weight_g', 'flow.flows.0.wavenet.in_layers.0.weight_v', 'flow.flows.0.wavenet.in_layers.1.weight_g', 'flow.flows.0.wavenet.in_layers.1.weight_v', 'flow.flows.0.wavenet.in_layers.2.weight_g', 'flow.flows.0.wavenet.in_layers.2.weight_v', 'flow.flows.0.wavenet.in_layers.3.weight_g', 'flow.flows.0.wavenet.in_layers.3.weight_v', 'flow.flows.0.wavenet.res_skip_layers.0.weight_g', 'flow.flows.0.wavenet.res_skip_layers.0.weight_v', 'flow.flows.0.wavenet.res_skip_layers.1.weight_g', 'flow.flows.0.wavenet.res_skip_layers.1.weight_v', 'flow.flows.0.wavenet.res_skip_layers.2.weight_g', 'flow.flows.0.wavenet.res_skip_layers.2.weight_v', 'flow.flows.0.wavenet.res_skip_layers.3.weight_g', 'flow.flows.0.wavenet.res_skip_layers.3.weight_v', 'flow.flows.1.wavenet.in_layers.0.weight_g', 'flow.flows.1.wavenet.in_layers.0.weight_v', 'flow.flows.1.wavenet.i

16000


In [32]:
text


'ہاں ضرور، میں مدد کرنے کا پابند ہوں گا۔'

In [1]:
text = "ہاں ضرور، میں مدد کرنے کا پابند ہوں گا۔"


In [ ]:
ہاں ضرور، میں مدد کرنے کا پابند ہوں گا۔


In [34]:
from IPython.display import Audio
Audio(audio, rate=18_000, autoplay=True)


In [35]:
audio


array([[-0.00046926, -0.0003878 , -0.00015942, ...,  0.00064625,
         0.00022941,  0.00040167]], dtype=float32)

In [4]:
from transformers import VitsModel, AutoTokenizer
import torch

model = VitsModel.from_pretrained("facebook/mms-tts-urd-script_arabic")
tokenizer = AutoTokenizer.from_pretrained("facebook/mms-tts-urd-script_arabic")

inputs = tokenizer(text, return_tensors="pt")

with torch.no_grad():
    output = model(**inputs).waveform


Some weights of the model checkpoint at facebook/mms-tts-urd-script_arabic were not used when initializing VitsModel: ['flow.flows.0.wavenet.in_layers.0.weight_g', 'flow.flows.0.wavenet.in_layers.0.weight_v', 'flow.flows.0.wavenet.in_layers.1.weight_g', 'flow.flows.0.wavenet.in_layers.1.weight_v', 'flow.flows.0.wavenet.in_layers.2.weight_g', 'flow.flows.0.wavenet.in_layers.2.weight_v', 'flow.flows.0.wavenet.in_layers.3.weight_g', 'flow.flows.0.wavenet.in_layers.3.weight_v', 'flow.flows.0.wavenet.res_skip_layers.0.weight_g', 'flow.flows.0.wavenet.res_skip_layers.0.weight_v', 'flow.flows.0.wavenet.res_skip_layers.1.weight_g', 'flow.flows.0.wavenet.res_skip_layers.1.weight_v', 'flow.flows.0.wavenet.res_skip_layers.2.weight_g', 'flow.flows.0.wavenet.res_skip_layers.2.weight_v', 'flow.flows.0.wavenet.res_skip_layers.3.weight_g', 'flow.flows.0.wavenet.res_skip_layers.3.weight_v', 'flow.flows.1.wavenet.in_layers.0.weight_g', 'flow.flows.1.wavenet.in_layers.0.weight_v', 'flow.flows.1.wavenet.i

In [5]:
output1, output2


(tensor([[-0.0004, -0.0005, -0.0003,  ..., -0.0008, -0.0013, -0.0009]]),
 VitsModelOutput(waveform=tensor([[-0.0014, -0.0016, -0.0014,  ..., -0.0019, -0.0022, -0.0020]]), sequence_lengths=tensor([50432]), spectrogram=tensor([[[ 1.3448,  0.2974,  0.5959,  ...,  1.3180,  0.5325,  0.8686],
          [ 0.0827,  0.6797,  0.3541,  ...,  0.9537,  1.0137,  0.7204],
          [ 1.0800,  0.2830,  1.1885,  ...,  0.5861,  1.8095,  0.9029],
          ...,
          [ 2.1765,  2.6938,  2.4807,  ...,  3.4345,  2.8606,  3.0540],
          [ 1.0320,  1.8655,  1.7557,  ...,  1.6762,  1.3349,  1.5286],
          [-0.0789, -0.2812,  0.5236,  ...,  0.2870,  0.0486,  0.1549]]]), hidden_states=None, attentions=None))

In [7]:
from IPython.display import Audio

Audio(output1, rate=model.config.sampling_rate)


In [ ]:
text = "ہاں ضرور، میں مدد کرنے کا پابند ہوں گا۔"

model_id = "facebook/mms-tts-urd-script_arabic"
mouth = Mouth_hf(model_id=model_id, device=device, forward_params={"speaker_id": 10})
mouth.say_text(text)
